name: Node Continuous Integration

on:
  check_suite:
    types:
      - completed
  pull_request:
    branches: [master]

jobs:
  auto_approve_3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: echo "PR prevented"
  
  throw_failure:
    if: startsWith(github.head_ref, 'github-action')
    runs-on: ubuntu-latest
    needs: auto_approve_3
    steps:
      - run: |
          echo "Forcing failure" && \
            echo "Testing multiline command" \
            && exit 1
          
