name: Node Continuous Integration

on:
  pull_request:
    branches: [master]

jobs:
  auto_approve_3:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - uses: hmarr/auto-approve-action@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - run: echo "PR prevented"
