name: PR approval info

on:
  pull_request_review:
    types:
      - submitted
        

jobs:
  count_reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.listReviews({
              pull_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            }).then(res => {
              const reviews = res.data;
              console.log(reviews);
              const reviewCount = new Set(reviews.filter(({ state }) => state === 'APPROVED').map(({ user }) => user.id)).size;
              if (reviewCount < 3) throw new Error("You require at least 3 reviews for this PR");
            });
            
            
