name: Scheduled test

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  pre_build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Starting builder
        run: echo "Starting builder"
      - name: Create local changes
        run: node builder
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: github-action-changes
      - name: Commit Completion message
        run: echo "Updated code"
      - name: Open PR
        uses: smartinspereira/auto-create-pr-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        env:
          BRANCH_PREFIX: github-action-changes
          PULL_REQUEST_TITLE: Merging updated time
