name: Scheduled test

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "This is a test"
      - run: echo "This a printed line"
      - run: echo "This is another line"
